### ISSUE TITLE
overflow?

### ISSUE THREAD

**Issue by yonromai** [cudabigdata/word2vec_cuda#1]
Hi, thanks a lot for sharing this code.

I tried to play around a bit with it today and although it works on the google demo dataset, it crashes on my dataset:

```
Starting training using file [...]
Vocab size: 1194363
Words in train file: -1153118731
Device Number: 0
  Device name: GeForce GTX 780 Ti
  Memory Clock Rate (KHz): 3500000
  Memory Bus Width (bits): 384
  Peak Memory Bandwidth (GB/s): 336.000000

CUDA error: no error: cbow.cu, line 226
```

I don't face this problem when I use google's w2v. After a quick look at `word2vec.cpp`, I noticed that you're using `int` instead of `long long` which I guess could cause this overflow. Is there any reason for this?

Thanks,

**Comment by cudabigdata** [comment]
Yes. You are right. It may overflow with large data set. Could fix this byte using int64. I have OpenCL version for this, too. (Could run on AMD GPU).

**Comment by yonromai** [comment]
Alright, good to know. I guess it would be super useful to have this code work for large dataset, which might be a major reason for using a GPU implementation in the first place

**Comment by cudabigdata** [comment]
Sure. I will fix this soon. (I fixed this issue  in OpenCL version, but I've not updated this CUDA version).
